[tool.poetry]
name = "test2"
version = "0.1.0"
description = ""
authors = ["kseniaa1 <poliakovakseniaa1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt6 = "^6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
